# backup running configuration

---

- name: Uses ansible_date_time fact to get system time and save it a variable
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Get date from system
      shell: "date +%Y-%m-%d%H-%M-%S"
      register: dstamp

    - name: create folder
      file:
        path: ~/ansible_test/configur_backup/{{dstamp.stdout[0:10]}}
        state: directory


    - name: define variable
      set_fact:
        today: "{{dstamp.stdout[0:10]}}"
        time: "{{dstamp.stdout[10:]}}"



- name: Backup router running configuration
  hosts: IOS

  tasks:
    - name: save to file
      ios_config:
        backup: yes
        backup_options:
          filename: "{{inventory_hostname}}_{{hostvars.localhost.time}}.txt"
          dir_path: ~/ansible_test/configur_backup/{{hostvars.localhost.today}}
