---

- name: Backup router running configuration
  hosts: IOS
  gather_facts: true

  tasks:
    - name: print out data type
      debug:
        msg:
          - "{{ ansible_facts.net_interfaces | type_debug }}"
          - "{{ ansible_facts.net_all_ipv4_addresses[0] }}"
          - "{{ ansible_facts.net_interfaces.GigabitEthernet1.ipv4[0] }}"
    - name: loop interfaces
      debug:
        msg:
          - "Key is {{ item.key }} and ipv4 value is {{ item.value.ipv4 }}"
      loop: "{{ ansible_facts.net_interfaces | dict2items}}"
    - name: get certain data using json_query
      debug:
        msg:
          - "{{ item.key }}"
          - "{{ item | dict2items | json_query('[].value.ipv4[].address') }}"
      loop: "{{ ansible_facts.net_interfaces | dict2items}}"
